# Generated by Django 5.0.1 on 2024-01-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_fname', models.CharField(max_length=15)),
                ('author_lname', models.CharField(max_length=15)),
                ('author_bod', models.DateField()),
                ('isbn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorBookAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField()),
                ('isbn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('statuss', models.CharField(default='Available', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('edition_id', models.IntegerField()),
                ('language_id', models.IntegerField()),
                ('availability_status_id', models.IntegerField()),
                ('publisher_id', models.IntegerField()),
                ('genre_id', models.IntegerField()),
                ('review_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookEdition',
            fields=[
                ('edition_id', models.AutoField(primary_key=True, serialize=False)),
                ('edition_name', models.CharField(max_length=50)),
                ('publication_date', models.DateField(default=models.DateField(auto_now_add=True))),
                ('formatt', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookGenreAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField()),
                ('genre_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('fine_id', models.AutoField(primary_key=True, serialize=False)),
                ('fine_amount', models.IntegerField()),
                ('fine_reason', models.CharField(max_length=50)),
                ('fine_pay_status', models.CharField(max_length=15)),
                ('member_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=50)),
                ('genre_description', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryBranch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=50)),
                ('branch_location', models.CharField(max_length=50)),
                ('branch_contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_date', models.DateField()),
                ('due_date', models.DateField()),
                ('return_date', models.DateField()),
                ('fine_amount', models.IntegerField()),
                ('loan_status', models.CharField(default='On Loan', max_length=50)),
                ('isbn', models.IntegerField()),
                ('member_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(max_length=50)),
                ('publisher_contact', models.CharField(max_length=50)),
                ('publisher_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateField()),
                ('reservation_status', models.CharField(default='Pending', max_length=15)),
                ('isbn', models.IntegerField()),
                ('member_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=10)),
                ('review_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('shelf_id', models.AutoField(primary_key=True, serialize=False)),
                ('shelf_number', models.IntegerField()),
                ('shelf_capacity', models.IntegerField(default=20)),
                ('shelf_type', models.CharField(max_length=50)),
                ('isbn', models.IntegerField()),
                ('branch_id', models.IntegerField()),
            ],
        ),
    ]
