# Generated by Django 5.0.1 on 2024-01-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DATABASE_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Latin1_General_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Latin1_General_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Latin1_General_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Latin1_General_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAppAuthor',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_fname', models.CharField(db_collation='Latin1_General_CI_AS', max_length=15)),
                ('author_lname', models.CharField(db_collation='Latin1_General_CI_AS', max_length=15)),
                ('author_bod', models.DateField()),
                ('isbn', models.IntegerField()),
            ],
            options={
                'db_table': 'DATABASE_APP_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAppAuthorbookassociation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author_id', models.IntegerField()),
                ('isbn', models.IntegerField()),
            ],
            options={
                'db_table': 'DATABASE_APP_authorbookassociation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAppAvailabilitystatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('statuss', models.CharField(db_collation='Latin1_General_CI_AS', max_length=15)),
            ],
            options={
                'db_table': 'DATABASE_APP_availabilitystatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAppBook',
            fields=[
                ('isbn', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_collation='Latin1_General_CI_AS', max_length=50)),
                ('edition_id', models.IntegerField()),
                ('language_id', models.IntegerField()),
                ('availability_status_id', models.IntegerField()),
                ('publisher_id', models.IntegerField()),
                ('genre_id', models.IntegerField()),
                ('review_id', models.IntegerField()),
            ],
            options={
                'db_table': 'DATABASE_APP_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAppBookedition',
            fields=[
                ('edition_id', models.AutoField(primary_key=True, serialize=False)),
                ('edition_name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=50)),
                ('publication_date', models.DateField()),
                ('formatt', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'DATABASE_APP_bookedition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAppBookgenreassociation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('isbn', models.IntegerField()),
                ('genre_id', models.IntegerField()),
            ],
            options={
                'db_table': 'DATABASE_APP_bookgenreassociation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAppFine',
            fields=[
                ('fine_id', models.AutoField(primary_key=True, serialize=False)),
                ('fine_amount', models.IntegerField()),
                ('fine_reason', models.CharField(db_collation='Latin1_General_CI_AS', max_length=50)),
                ('fine_pay_status', models.CharField(db_collation='Latin1_General_CI_AS', max_length=15)),
                ('member_id', models.IntegerField()),
            ],
            options={
                'db_table': 'DATABASE_APP_fine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAppGenre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=50)),
                ('genre_description', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'DATABASE_APP_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAppLanguage',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=15)),
            ],
            options={
                'db_table': 'DATABASE_APP_language',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAppLibrarybranch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=50)),
                ('branch_location', models.CharField(db_collation='Latin1_General_CI_AS', max_length=50)),
                ('branch_contact', models.CharField(db_collation='Latin1_General_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'DATABASE_APP_librarybranch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAppLoan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_date', models.DateField()),
                ('due_date', models.DateField()),
                ('return_date', models.DateField()),
                ('fine_amount', models.IntegerField()),
                ('loan_status', models.CharField(db_collation='Latin1_General_CI_AS', max_length=50)),
                ('isbn', models.IntegerField()),
                ('member_id', models.IntegerField()),
            ],
            options={
                'db_table': 'DATABASE_APP_loan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAppPublisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=50)),
                ('publisher_contact', models.CharField(db_collation='Latin1_General_CI_AS', max_length=50)),
                ('publisher_address', models.CharField(db_collation='Latin1_General_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'DATABASE_APP_publisher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAppReservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateField()),
                ('reservation_status', models.CharField(db_collation='Latin1_General_CI_AS', max_length=15)),
                ('isbn', models.IntegerField()),
                ('member_id', models.IntegerField()),
            ],
            options={
                'db_table': 'DATABASE_APP_reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAppReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(db_collation='Latin1_General_CI_AS', max_length=10)),
                ('review_date', models.DateField()),
            ],
            options={
                'db_table': 'DATABASE_APP_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAppShelf',
            fields=[
                ('shelf_id', models.AutoField(primary_key=True, serialize=False)),
                ('shelf_number', models.IntegerField()),
                ('shelf_capacity', models.IntegerField()),
                ('shelf_type', models.CharField(db_collation='Latin1_General_CI_AS', max_length=50)),
                ('isbn', models.IntegerField()),
                ('branch_id', models.IntegerField()),
            ],
            options={
                'db_table': 'DATABASE_APP_shelf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='Latin1_General_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Latin1_General_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Latin1_General_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Latin1_General_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Latin1_General_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Latin1_General_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Latin1_General_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('librarian_id', models.IntegerField(db_column='LIBRARIAN_ID', primary_key=True, serialize=False)),
                ('librarian_fname', models.CharField(db_collation='Latin1_General_CI_AS', db_column='LIBRARIAN_FNAME', max_length=50)),
                ('librarian_lname', models.CharField(db_collation='Latin1_General_CI_AS', db_column='LIBRARIAN_LNAME', max_length=50)),
                ('librarian_contact', models.CharField(db_collation='Latin1_General_CI_AS', db_column='LIBRARIAN_CONTACT', max_length=50)),
            ],
            options={
                'db_table': 'LIBRARIAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.IntegerField(db_column='MEMBER_ID', primary_key=True, serialize=False)),
                ('member_fname', models.CharField(db_collation='Latin1_General_CI_AS', db_column='MEMBER_FNAME', max_length=15)),
                ('member_lname', models.CharField(db_collation='Latin1_General_CI_AS', db_column='MEMBER_LNAME', max_length=15)),
                ('member_contact', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='MEMBER_CONTACT', max_length=50, null=True)),
                ('member_email', models.CharField(db_collation='Latin1_General_CI_AS', db_column='MEMBER_EMAIL', max_length=50, unique=True)),
                ('member_address', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='MEMBER_ADDRESS', max_length=50, null=True)),
                ('membership_status', models.CharField(db_collation='Latin1_General_CI_AS', db_column='MEMBERSHIP_STATUS', max_length=15)),
            ],
            options={
                'db_table': 'MEMBER_',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authorbookassociation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='availabilitystatus',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bookedition',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bookgenreassociation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fine',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='librarybranch',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='shelf',
            options={'managed': False},
        ),
    ]
